name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eb300e773de178e9edd255a01a2c40b7524235ed39a7f615c47afc7d1587132"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
