name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70923873f5b7455050d1e751c3c76eb206beaba6ce209281ce5eebe753fc6533"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
