name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59202a3d83eeaeb710a6a4dd72b7057d2ee9eb6734f72e68dca3d0dc23c5f4fb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
